replicaCount: 2 # כמה עותקים של האפליקציה ירוצו (לצורך שרידות)

image:
  repository: 639418629537.dkr.ecr.us-east-1.amazonaws.com/app-repo-new
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer # זה מה שיוצר כתובת אינטרנט ציבורית ב-AWS
  port: 80           # הפורט החיצוני שהעולם רואה
  targetPort: 5000   # הפורט הפנימי של ה-Flask